src/config/routes.rb
Rails.application.routes.draw do
  resources :parking_areas
  root 'place_parkings#index'

  resources :place_parkings

end

src/app/models/parking_area.rb
class ParkingArea < ActiveRecord::Base
end

src/app/models/place_parking.rb
class PlaceParking < ActiveRecord::Base
end

src/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

src/app/controllers/parking_areas_controller.rb
class ParkingAreasController < ApplicationController
  before_action :set_parking_area, only: [:show, :edit, :update, :destroy]

  # GET /parking_areas
  # GET /parking_areas.json
  def index
    @parking_areas = ParkingArea.all
  end

  # GET /parking_areas/1
  # GET /parking_areas/1.json
  def show
  end

  # GET /parking_areas/new
  def new
    @parking_area = ParkingArea.new
  end

  # GET /parking_areas/1/edit
  def edit
  end

  # POST /parking_areas
  # POST /parking_areas.json
  def create
    @parking_area = ParkingArea.new(parking_area_params)

    respond_to do |format|
      if @parking_area.save
        format.html { redirect_to @parking_area, notice: 'Parking area was successfully created.' }
        format.json { render :show, status: :created, location: @parking_area }
      else
        format.html { render :new }
        format.json { render json: @parking_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parking_areas/1
  # PATCH/PUT /parking_areas/1.json
  def update
    respond_to do |format|
      if @parking_area.update(parking_area_params)
        format.html { redirect_to @parking_area, notice: 'Parking area was successfully updated.' }
        format.json { render :show, status: :ok, location: @parking_area }
      else
        format.html { render :edit }
        format.json { render json: @parking_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parking_areas/1
  # DELETE /parking_areas/1.json
  def destroy
    @parking_area.destroy
    respond_to do |format|
      format.html { redirect_to parking_areas_url, notice: 'Parking area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking_area
      @parking_area = ParkingArea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parking_area_params
      params.require(:parking_area).permit(:capacity)
    end
end

src/app/controllers/place_parkings_controller.rb
class PlaceParkingsController < ApplicationController
  before_action :set_place_parking, only: [:show, :edit, :update, :destroy]

  # GET /place_parkings
  # GET /place_parkings.json
  def index
    @place_parkings = PlaceParking.all
  end

  # GET /place_parkings/1
  # GET /place_parkings/1.json
  def show
  end

  # GET /place_parkings/new
  def new
    @place_parking = PlaceParking.new
  end

  # GET /place_parkings/1/edit
  def edit
  end

  # POST /place_parkings
  # POST /place_parkings.json
  def create
    @place_parking = PlaceParking.new(place_parking_params)

    respond_to do |format|
      if @place_parking.save
        format.html { redirect_to @place_parking, notice: 'Place parking was successfully created.' }
        format.json { render :show, status: :created, location: @place_parking }
      else
        format.html { render :new }
        format.json { render json: @place_parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /place_parkings/1
  # PATCH/PUT /place_parkings/1.json
  def update
    respond_to do |format|
      if @place_parking.update(place_parking_params)
        format.html { redirect_to @place_parking, notice: 'Place parking was successfully updated.' }
        format.json { render :show, status: :ok, location: @place_parking }
      else
        format.html { render :edit }
        format.json { render json: @place_parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /place_parkings/1
  # DELETE /place_parkings/1.json
  def destroy
    @place_parking.destroy
    respond_to do |format|
      format.html { redirect_to place_parkings_url, notice: 'Place parking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place_parking
      @place_parking = PlaceParking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_parking_params
      params.require(:place_parking).permit(:slot_number, :registration_number, :color)
    end
end

src/app/helpers/application_helper.rb
module ApplicationHelper
end

src/app/helpers/parking_areas_helper.rb
module ParkingAreasHelper
end

src/app/helpers/place_parkings_helper.rb
module PlaceParkingsHelper
end

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

src/app/views/parking_areas/_form.html.erb
<%= form_for(@parking_area) do |f| %>
  <% if @parking_area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parking_area.errors.count, "error") %> prohibited this parking_area from being saved:</h2>

      <ul>
      <% @parking_area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.check_box :capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/parking_areas/edit.html.erb
<h1>Editing Parking Area</h1>

<%= render 'form' %>

<%= link_to 'Show', @parking_area %> |
<%= link_to 'Back', parking_areas_path %>

src/app/views/parking_areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Parking Areas</h1>

<table>
  <thead>
    <tr>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parking_areas.each do |parking_area| %>
      <tr>
        <td><%= parking_area.capacity %></td>
        <td><%= link_to 'Show', parking_area %></td>
        <td><%= link_to 'Edit', edit_parking_area_path(parking_area) %></td>
        <td><%= link_to 'Destroy', parking_area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parking area', new_parking_area_path %>

src/app/views/parking_areas/new.html.erb
<h1>New Parking Area</h1>

<%= render 'form' %>

<%= link_to 'Back', parking_areas_path %>

src/app/views/parking_areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Capacity:</strong>
  <%= @parking_area.capacity %>
</p>

<%= link_to 'Edit', edit_parking_area_path(@parking_area) %> |
<%= link_to 'Back', parking_areas_path %>

src/app/views/place_parkings/_form.html.erb
<%= form_for(@place_parking) do |f| %>
  <% if @place_parking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place_parking.errors.count, "error") %> prohibited this place_parking from being saved:</h2>

      <ul>
      <% @place_parking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :slot_number %><br>
    <%= f.number_field :slot_number %>
  </div>
  <div class="field">
    <%= f.label :registration_number %><br>
    <%= f.text_field :registration_number %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

src/app/views/place_parkings/edit.html.erb
<h1>Editing Place Parking</h1>

<%= render 'form' %>

<%= link_to 'Show', @place_parking %> |
<%= link_to 'Back', place_parkings_path %>

src/app/views/place_parkings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Place Parkings</h1>

<table>
  <thead>
    <tr>
      <th>Slot number</th>
      <th>Registration number</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @place_parkings.each do |place_parking| %>
      <tr>
        <td><%= place_parking.slot_number %></td>
        <td><%= place_parking.registration_number %></td>
        <td><%= place_parking.color %></td>
        <td><%= link_to 'Show', place_parking %></td>
        <td><%= link_to 'Edit', edit_place_parking_path(place_parking) %></td>
        <td><%= link_to 'Destroy', place_parking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place parking', new_place_parking_path %>

src/app/views/place_parkings/new.html.erb
<h1>New Place Parking</h1>

<%= render 'form' %>

<%= link_to 'Back', place_parkings_path %>

src/app/views/place_parkings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Slot number:</strong>
  <%= @place_parking.slot_number %>
</p>

<p>
  <strong>Registration number:</strong>
  <%= @place_parking.registration_number %>
</p>

<p>
  <strong>Color:</strong>
  <%= @place_parking.color %>
</p>

<%= link_to 'Edit', edit_place_parking_path(@place_parking) %> |
<%= link_to 'Back', place_parkings_path %>